import { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import rehypeRaw from 'rehype-raw';
import { Copy, ChevronDown, ChevronRight, Check, ThumbsUp, ThumbsDown, RotateCcw, Share2, FileText, Brain, ExternalLink, Sparkles } from 'lucide-react';
import type { Citation, Message } from '../hooks/useChat';
import { useToast } from './Toast';
const userAvatarImg = '/user_avatar.png';
const botAvatarImg = '/bot_avatar.png';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "/api";

interface ChatMessageProps {
  message: Message;
  thinkingMessage?: string;
  onRegenerate?: () => void;
  onRetry?: () => void;
  query?: string;
  onSuggestionClick?: (text: string) => void;
}


function getRelativeTime(timestamp: string): string {
  // Simple implementation since timestamp is just HH:MM
  return timestamp;
}

// eslint-disable-next-line react-refresh/only-export-components
export function formatCitationContent(text: string): string {
  let cleaned = text;
  // Strip out the metadata prefix generated by the chunker
  if (cleaned.includes('Nội dung:')) {
    cleaned = cleaned.split('Nội dung:').slice(1).join('Nội dung:').trim();
  }
  
  // Automatically add line breaks before list items to make it readable
  cleaned = cleaned.replace(/(^|\s)(\d+\.)\s/g, '\n\n**$2** ');
  cleaned = cleaned.replace(/(^|\s)([a-z]\))\s/g, '\n\n  *$2* ');
  cleaned = cleaned.replace(/(^|\s)([-•])\s/g, '\n\n$2 ');
  cleaned = cleaned.replace(/:\s/g, ':\n\n');
  
  return cleaned.trim();
}

function formatCitationContentForDisplay(text: string): string {
  let cleaned = text;

  if (cleaned.includes('THÔNG TIN TRỌNG TÂM ĐÃ TÁCH TỪ NGUỒN:')) {
    cleaned = cleaned.split('THÔNG TIN TRỌNG TÂM ĐÃ TÁCH TỪ NGUỒN:')[0].trim();
  }

  if (cleaned.includes('Nội dung:')) {
    cleaned = cleaned.split('Nội dung:').slice(1).join('Nội dung:').trim();
  }

  return cleaned
    .replace(/(?:^|\n)(\d+\.)\s/g, '\n\n**$1** ')
    .replace(/(?:^|\n)([a-zđ]\))\s/gi, '\n\n*$1* ')
    .replace(/(?:^|\n)([-•])\s/g, '\n\n$1 ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function normalizeCitationLabel(value?: string): string {
  const text = (value || '').trim();
  if (!text) return '';

  const normalized = text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[–—]/g, '-')
    .replace(/\s+/g, ' ');

  const labelMap: Record<string, string> = {
    'danh sach nganh dao tao': 'Danh sách ngành đào tạo',
    'danh muc nganh dao tao trong so tay sinh vien hcmue': 'Danh mục ngành đào tạo trong Sổ tay sinh viên HCMUE',
    'program directory': 'Danh sách ngành đào tạo',
    'program_directory': 'Danh sách ngành đào tạo',
    'faculty directory': 'Danh bạ khoa/đơn vị',
    'faculty_directory': 'Danh bạ khoa/đơn vị',
    'office directory': 'Danh bạ phòng ban',
    'office_directory': 'Danh bạ phòng ban',
    'form templates': 'Biểu mẫu',
    'form_templates': 'Biểu mẫu',
    'scoring tables': 'Bảng điểm',
    'scoring_tables': 'Bảng điểm',
    'threshold rules': 'Quy định ngưỡng điểm',
    'threshold_rules': 'Quy định ngưỡng điểm',
    'regulation sections': 'Quy định',
    'regulation_sections': 'Quy định',
  };

  return labelMap[normalized] || text;
}

function getCitationTypeLabel(citation: Citation): string {
  const sourceLabel = normalizeCitationLabel(citation.source_label);
  if (sourceLabel) return sourceLabel;
  switch (citation.chunk_type) {
    case 'structured_lookup':
      return 'Bảng quy định';
    case 'program_directory':
      return 'Danh sách ngành đào tạo';
    case 'faculty_directory':
      return 'Danh bạ khoa/đơn vị';
    case 'office_directory':
      return 'Danh bạ phòng ban';
    case 'form_templates':
      return 'Biểu mẫu';
    case 'formula':
      return 'Công thức/quy tắc';
    case 'form':
      return 'Biểu mẫu';
    case 'contact':
      return 'Liên hệ';
    case 'procedure':
      return 'Quy trình';
    case 'rule':
      return 'Quy định';
    default:
      return 'Nguồn tham khảo';
  }
}

function getCompactExcerpt(text: string, maxLength = 220): string {
  const plain = formatCitationContentForDisplay(text)
    .replace(/\*\*/g, '')
    .replace(/\n+/g, ' ')
    .trim();
  if (plain.length <= maxLength) return plain;
  return `${plain.slice(0, maxLength).trim()}...`;
}

function highlightKeywords(text: string, query?: string): string {
  if (!query) return text;
  
  const cleanQuery = query.replace(/[?!.,;]/g, '').toLowerCase().trim();
  const words = cleanQuery.split(/\s+/);
  
  const phrases: string[] = [];
  
  // Create N-grams (from 4 words down to 2 words)
  const maxN = Math.min(words.length, 4);
  for (let n = maxN; n >= 2; n--) {
    for (let i = 0; i <= words.length - n; i++) {
      phrases.push(words.slice(i, i + n).join(' '));
    }
  }
  
  // Only add single words if they are long enough (e.g. English keywords like "deadline", "scholarship")
  // Or if the user only typed exactly 1 word
  if (words.length === 1) {
    phrases.push(words[0]);
  } else {
    words.forEach(w => {
      if (w.length > 5) phrases.push(w);
    });
  }
  
  // Filter out common stop phrases and short phrases
  const stopPhrases = ['là gì', 'như thế nào', 'ở đâu', 'thế nào', 'khi nào', 'có được', 'không được', 'cho tôi', 'làm sao'];
  const validPhrases = [...new Set(phrases)]
    .filter(p => p.length > 2 && !stopPhrases.includes(p))
    .sort((a, b) => b.length - a.length); // Sort longest first
    
  if (validPhrases.length === 0) return text;
  
  // Escape regex special chars
  const escapeRegex = (s: string) => s.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
  
  // Build a single Regex with alternation: (phrase1|phrase2|...)
  // This single-pass replacement prevents nested <mark> tags!
  const pattern = new RegExp(`(${validPhrases.map(escapeRegex).join('|')})`, 'gi');
  
  return text.replace(pattern, '<mark>$1</mark>');
}

export function ChatMessage({ message, thinkingMessage = "", onRegenerate, onRetry, query, onSuggestionClick }: ChatMessageProps) {
  const defaultShowSources = !!(message.citations && message.citations.length > 0 && message.citations.length <= 2);
  const [showSources, setShowSources] = useState(defaultShowSources);
  const [expandedCitations, setExpandedCitations] = useState<Set<number>>(new Set());
  const [copied, setCopied] = useState(false);

  const toggleCitation = (idx: number) => {
    setExpandedCitations(prev => {
      const newSet = new Set(prev);
      if (newSet.has(idx)) {
        newSet.delete(idx);
      } else {
        newSet.add(idx);
      }
      return newSet;
    });
  };
  const [feedback, setFeedback] = useState<'like'|'dislike'|null>(null);
  const toast = useToast();

  const [showInlineFeedback, setShowInlineFeedback] = useState(false);
  const [feedbackText, setFeedbackText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showThinking, setShowThinking] = useState(false);
  const [justFinished, setJustFinished] = useState(false);
  const feedbackInputRef = useRef<HTMLTextAreaElement>(null);
  const prevStreamingRef = useRef(message.isStreaming);

  useEffect(() => {
    if (showInlineFeedback && feedbackInputRef.current) {
        feedbackInputRef.current.focus();
        feedbackInputRef.current.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }, [showInlineFeedback]);

  useEffect(() => {
    if (prevStreamingRef.current === true && message.isStreaming === false) {
       setJustFinished(true);
       setTimeout(() => setJustFinished(false), 2000);
    }
    prevStreamingRef.current = message.isStreaming;
  }, [message.isStreaming]);

  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
    toast.show("Đã sao chép nội dung!", "success");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = () => {
    const text = `📚 HCMUE AI Assistant\n\n💬 ${message.content}\n\n🔗 https://hcmuebot.id.vn`;
    navigator.clipboard.writeText(text);
    toast.show("Đã sao chép nội dung để chia sẻ!", "success");
  };

  const submitFeedbackToApi = async (type: 'like' | 'dislike', text: string = "") => {
    if (!message.runId) return;
    setIsSubmitting(true);
    try {
      await fetch(`${API_BASE_URL}/chat/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          run_id: message.runId,
          score: type === 'like' ? 1.0 : 0.0,
          comment: text || undefined
        })
      });
      toast.show("Cảm ơn bạn đã đánh giá!", "success");
    } catch {
      toast.show("Có lỗi xảy ra khi gửi đánh giá.", "error");
    } finally {
      setIsSubmitting(false);
      setShowInlineFeedback(false);
    }
  };

  const handleFeedbackClick = (type: 'like' | 'dislike') => {
    if (feedback !== null) return;
    setFeedback(type);
    if (type === 'dislike' && message.runId) {
      setShowInlineFeedback(true);
      setFeedbackText("");
    } else if (type === 'like' && message.runId) {
      submitFeedbackToApi('like');
    } else {
      toast.show("Cảm ơn bạn đã đánh giá!", "success");
    }
  };

  if (message.role === 'user') {
    return (
      <div className="message-wrapper user">
        <img src={userAvatarImg} alt="User" className="avatar user" style={{ backgroundColor: 'transparent' }} />
        <div className="message-content">
          <div className="message-header">
            <span className="message-time">{getRelativeTime(message.timestamp)}</span>
          </div>
          <div className="message-bubble">
            {message.content}
          </div>
        </div>
      </div>
    );
  }

  const isErrorMsg = !message.isStreaming && message.content.includes("Xin lỗi, đã có lỗi");

  let displayContent = message.content;
  let thinkContent = "";
  
  const thinkMatch = displayContent.match(/<think>([\s\S]*?)<\/think>/);
  if (thinkMatch) {
    thinkContent = thinkMatch[1].trim();
    displayContent = displayContent.replace(/<think>[\s\S]*?<\/think>/, '').trim();
  } else if (displayContent.includes('<think>')) {
    const parts = displayContent.split('<think>');
    displayContent = parts[0].trim();
    thinkContent = parts[1].trim();
  }

  return (
    <div className="message-wrapper bot">
      <img src={botAvatarImg} alt="HCMUE AI" className="avatar bot" />
      <div className="message-content">
        <div className={`message-bubble ${message.isStreaming && !displayContent && !thinkContent && !thinkingMessage ? 'typing-indicator' : ''}`}>
          {message.isStreaming && !displayContent && !thinkContent ? (
            thinkingMessage ? (
              <div className="cold-start-content" style={{ padding: '2px 4px' }}>
                <Sparkles size={18} className="thinking-sparkle" />
                <span className="thinking-text">{thinkingMessage}</span>
              </div>
            ) : (
              <>
                <div className="typing-dot"></div>
                <div className="typing-dot"></div>
                <div className="typing-dot"></div>
              </>
            )
          ) : (
            <>
              {thinkContent && (
                <div className="thinking-block" style={{ marginBottom: '1rem', borderLeft: '3px solid var(--border-color)', paddingLeft: '0.75rem' }}>
                  <div 
                    className="thinking-header" 
                    onClick={() => setShowThinking(!showThinking)}
                    style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: showThinking ? '0.5rem' : '0' }}
                  >
                    <Brain size={16} />
                    <span>Quá trình suy luận</span>
                    {showThinking ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                  </div>
                  {showThinking && (
                    <div className="thinking-content" style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', fontStyle: 'italic', whiteSpace: 'pre-wrap' }}>
                      {thinkContent}
                    </div>
                  )}
                </div>
              )}
              {displayContent && <ReactMarkdown>{displayContent}</ReactMarkdown>}
            </>
          )}
          
          {message.isStreaming && displayContent && (
            <span style={{ display: 'inline-block', width: '8px', height: '16px', background: 'var(--accent-color)', animation: 'blink 1s step-end infinite', marginLeft: '4px', verticalAlign: 'middle' }}></span>
          )}

          {!message.isStreaming && message.citations && message.citations.length > 0 && (
            <div className="citation-container">
              <div 
                className="citation-header" 
                onClick={() => setShowSources(!showSources)}
                style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-secondary)' }}
              >
                <span>Nguồn tham khảo ({message.citations.length})</span>
                {showSources ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
              </div>
              
              {showSources && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginTop: '0.5rem' }}>
                  {message.citations.map((cit, idx) => {
                    const isExpanded = expandedCitations.has(idx);
                    const pagesLabel = cit.source_pages?.length ? `Trang ${cit.source_pages.join(', ')}` : '';
                    const excerpt = cit.content ? getCompactExcerpt(cit.content) : '';
                    const citationTitle = normalizeCitationLabel(cit.title || cit.chunk_id);
                    const applicability = normalizeCitationLabel(cit.applicability);
                    return (
                      <div key={idx} className="citation-card">
                        <div className="citation-card-header" onClick={() => toggleCitation(idx)}>
                          <div className="citation-card-icon"><FileText size={16} /></div>
                          <div className="citation-card-body">
                            <span className="citation-title">{citationTitle}</span>
                            <div className="citation-meta-row">
                              <span className="citation-badge">{getCitationTypeLabel(cit)}</span>
                              {cit.cohort && <span className="citation-badge">{cit.cohort}</span>}
                              {pagesLabel && <span className="citation-pages">{pagesLabel}</span>}
                            </div>
                            {applicability && <span className="citation-applicability">{applicability}</span>}
                            {!isExpanded && excerpt && (
                              <div className="citation-excerpt-wrap">
                                <span className="citation-excerpt-label">Trích đoạn liên quan</span>
                                <p className="citation-excerpt">{excerpt}</p>
                              </div>
                            )}
                          </div>
                          {cit.source_url && (
                            <a
                              className="citation-source-link"
                              href={cit.source_url}
                              target="_blank"
                              rel="noreferrer"
                              onClick={(event) => event.stopPropagation()}
                            >
                              <ExternalLink size={14} />
                              <span>Mở nguồn</span>
                            </a>
                          )}
                          <div className="citation-card-toggle">
                            {isExpanded ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                          </div>
                        </div>
                        {isExpanded && cit.content && (
                          <div className="citation-card-content citation-markdown">
                            <ReactMarkdown rehypePlugins={[rehypeRaw]}>
                              {highlightKeywords(formatCitationContentForDisplay(cit.content), query)}
                            </ReactMarkdown>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}
        </div>

        {isErrorMsg && (
          <button className="retry-btn" onClick={() => onRetry?.()}>
            <RotateCcw size={14} /> Thử lại
          </button>
        )}



        {!message.isStreaming && !isErrorMsg && (
          <div className="message-metadata" style={{ flexDirection: 'column', alignItems: 'stretch' }}>
            <div style={{ display: 'flex', width: '100%', alignItems: 'center' }}>
              <div className="meta-actions">
                <button className="action-btn" title="Chia sẻ" onClick={handleShare}>
                  <Share2 size={16} />
                  <span className="action-btn-label">Chia sẻ</span>
                </button>
                <button 
                  className={`action-btn ${feedback === 'like' ? 'active' : ''} ${justFinished ? 'pulse-glow' : ''}`} 
                  title="Hữu ích" 
                  onClick={() => handleFeedbackClick('like')}
                  disabled={feedback !== null}
                >
                  <ThumbsUp size={16} />
                </button>
                <button 
                  className={`action-btn ${feedback === 'dislike' ? 'active' : ''} ${justFinished ? 'pulse-glow' : ''}`} 
                  title="Chưa chính xác" 
                  onClick={() => handleFeedbackClick('dislike')}
                  disabled={feedback !== null}
                >
                  <ThumbsDown size={16} />
                </button>
                <button className="action-btn" title="Copy" onClick={handleCopy}>
                  {copied ? <Check size={16} style={{color: 'var(--success)'}}/> : <Copy size={16} />}
                  <span className="action-btn-label">{copied ? 'Đã copy' : 'Copy'}</span>
                </button>
                <button className="action-btn" title="Tạo lại" onClick={() => onRegenerate?.()}>
                  <RotateCcw size={16} />
                  <span className="action-btn-label">Tạo lại</span>
                </button>
              </div>
              
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginLeft: 'auto' }}>
              {message.usedCache ? (
                <span className="metadata-badge cache" title="Câu trả lời được lấy từ bộ nhớ đệm giúp tốc độ phản hồi tức thì">
                  ⚡ Từ bộ nhớ đệm
                </span>
              ) : (
                message.responseTimeMs && (
                  <span 
                    className="metadata-badge latency" 
                    title={`Tổng thời gian phản hồi: ${(message.responseTimeMs / 1000).toFixed(2)}s${message.ttftMs ? ` (Từ đầu tiên: ${(message.ttftMs / 1000).toFixed(2)}s)` : ''}`}
                  >
                    ⏱️ {(message.responseTimeMs / 1000).toFixed(1)}s
                  </span>
                )
              )}
            </div>
            </div>

            {showInlineFeedback && (
              <div className="inline-feedback-container">
                <div className="inline-feedback-header">
                  Câu trả lời sai hoặc thiếu thông tin gì? (Không bắt buộc)
                </div>
                <textarea 
                  ref={feedbackInputRef}
                  className="inline-feedback-input"
                  value={feedbackText} 
                  onChange={e => setFeedbackText(e.target.value)} 
                  placeholder="Ví dụ: Trả lời sai thông tin học bổng..."
                  rows={2}
                  disabled={isSubmitting}
                />
                <div className="inline-feedback-actions">
                  <button className="btn-secondary" onClick={() => setShowInlineFeedback(false)} disabled={isSubmitting}>Bỏ qua</button>
                  <button className="btn-primary" onClick={() => submitFeedbackToApi('dislike', feedbackText)} disabled={isSubmitting}>
                    {isSubmitting ? "Đang gửi..." : "Gửi góp ý"}
                  </button>
                </div>
              </div>
            )}

          </div>
        )}

        {!message.isStreaming && !isErrorMsg && message.role === 'bot' && message.suggestions && message.suggestions.length > 0 && (
          <div className="suggestion-pills-container">
            <span className="suggestion-pills-label">Hỏi nhanh:</span>
            {message.suggestions.slice(0, 6).map((sugg, idx) => (
              <button key={idx} className="suggestion-pill" onClick={() => {
                if (onSuggestionClick) onSuggestionClick(sugg);
              }}>
                {sugg}
              </button>
            ))}
          </div>
        )}


      </div>
    </div>
  );
}
