import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import rehypeRaw from 'rehype-raw';
import { Copy, ChevronDown, ChevronRight, Check, ThumbsUp, ThumbsDown, RotateCcw, Share2, FileText, X } from 'lucide-react';
import type { Message } from '../hooks/useChat';
import { useToast } from './Toast';
import userAvatarImg from '../assets/user_avatar.png';
import botAvatarImg from '../assets/bot_avatar.png';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "/api";

interface ChatMessageProps {
  message: Message;
  thinkingMessage?: string;
  onRegenerate?: () => void;
  onRetry?: () => void;
  query?: string;
  onSuggestionClick?: (text: string) => void;
}


function getRelativeTime(timestamp: string): string {
  // Simple implementation since timestamp is just HH:MM
  return timestamp;
}

function formatCitationContent(text: string): string {
  let cleaned = text;
  // Strip out the metadata prefix generated by the chunker
  if (cleaned.includes('Nội dung:')) {
    cleaned = cleaned.split('Nội dung:').slice(1).join('Nội dung:').trim();
  }
  
  // Automatically add line breaks before list items to make it readable
  cleaned = cleaned.replace(/(^|\s)(\d+\.)\s/g, '\n\n**$2** ');
  cleaned = cleaned.replace(/(^|\s)([a-z]\))\s/g, '\n\n  *$2* ');
  cleaned = cleaned.replace(/(^|\s)([-•])\s/g, '\n\n$2 ');
  cleaned = cleaned.replace(/:\s/g, ':\n\n');
  
  return cleaned.trim();
}

function highlightKeywords(text: string, query?: string): string {
  if (!query) return text;
  
  const cleanQuery = query.replace(/[?!.,;]/g, '').toLowerCase().trim();
  const words = cleanQuery.split(/\s+/);
  
  const phrases: string[] = [];
  
  // Create N-grams (from 4 words down to 2 words)
  const maxN = Math.min(words.length, 4);
  for (let n = maxN; n >= 2; n--) {
    for (let i = 0; i <= words.length - n; i++) {
      phrases.push(words.slice(i, i + n).join(' '));
    }
  }
  
  // Only add single words if they are long enough (e.g. English keywords like "deadline", "scholarship")
  // Or if the user only typed exactly 1 word
  if (words.length === 1) {
    phrases.push(words[0]);
  } else {
    words.forEach(w => {
      if (w.length > 5) phrases.push(w);
    });
  }
  
  // Filter out common stop phrases and short phrases
  const stopPhrases = ['là gì', 'như thế nào', 'ở đâu', 'thế nào', 'khi nào', 'có được', 'không được', 'cho tôi', 'làm sao'];
  const validPhrases = [...new Set(phrases)]
    .filter(p => p.length > 2 && !stopPhrases.includes(p))
    .sort((a, b) => b.length - a.length); // Sort longest first
    
  if (validPhrases.length === 0) return text;
  
  // Escape regex special chars
  const escapeRegex = (s: string) => s.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
  
  // Build a single Regex with alternation: (phrase1|phrase2|...)
  // This single-pass replacement prevents nested <mark> tags!
  const pattern = new RegExp(`(${validPhrases.map(escapeRegex).join('|')})`, 'gi');
  
  return text.replace(pattern, '<mark>$1</mark>');
}

export function ChatMessage({ message, thinkingMessage = "", onRegenerate, onRetry, query, onSuggestionClick }: ChatMessageProps) {
  const defaultShowSources = !!(message.citations && message.citations.length > 0 && message.citations.length <= 2);
  const [showSources, setShowSources] = useState(defaultShowSources);
  const [expandedCitations, setExpandedCitations] = useState<Set<number>>(new Set());
  const [copied, setCopied] = useState(false);

  const toggleCitation = (idx: number) => {
    setExpandedCitations(prev => {
      const newSet = new Set(prev);
      if (newSet.has(idx)) {
        newSet.delete(idx);
      } else {
        newSet.add(idx);
      }
      return newSet;
    });
  };
  const [feedback, setFeedback] = useState<'like'|'dislike'|null>(null);
  const toast = useToast();

  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [feedbackText, setFeedbackText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
    toast.show("Đã sao chép nội dung!", "success");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = () => {
    const text = `📚 HCMUE AI Assistant\n\n💬 ${message.content}\n\n🔗 https://hcmuebot.id.vn`;
    navigator.clipboard.writeText(text);
    toast.show("Đã sao chép nội dung để chia sẻ!", "success");
  };

  const submitFeedbackToApi = async (type: 'like' | 'dislike', text: string = "") => {
    if (!message.runId) return;
    setIsSubmitting(true);
    try {
      await fetch(`${API_BASE_URL}/chat/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          run_id: message.runId,
          score: type === 'like' ? 1.0 : 0.0,
          comment: text || undefined
        })
      });
      toast.show("Cảm ơn bạn đã đánh giá!", "success");
    } catch (err) {
      toast.show("Có lỗi xảy ra khi gửi đánh giá.", "error");
    } finally {
      setIsSubmitting(false);
      setShowFeedbackModal(false);
    }
  };

  const handleFeedbackClick = (type: 'like' | 'dislike') => {
    setFeedback(type);
    if (type === 'dislike' && message.runId) {
      setShowFeedbackModal(true);
      setFeedbackText("");
    } else if (type === 'like' && message.runId) {
      submitFeedbackToApi('like');
    } else {
      toast.show("Cảm ơn bạn đã đánh giá!", "success");
    }
  };

  if (message.role === 'user') {
    return (
      <div className="message-wrapper user">
        <img src={userAvatarImg} alt="User" className="avatar user" style={{ backgroundColor: 'transparent' }} />
        <div className="message-content">
          <div className="message-header">
            <span className="message-time">{getRelativeTime(message.timestamp)}</span>
          </div>
          <div className="message-bubble">
            {message.content}
          </div>
        </div>
      </div>
    );
  }

  const isErrorMsg = !message.isStreaming && message.content.includes("Xin lỗi, đã có lỗi");

  return (
    <div className="message-wrapper bot">
      <img src={botAvatarImg} alt="HCMUE AI" className="avatar bot" />
      <div className="message-content">
        <div className={`${thinkingMessage && message.isStreaming && !message.content ? 'cold-start-bubble' : 'message-bubble'} ${message.isStreaming && !message.content && !thinkingMessage ? 'typing-indicator' : ''}`}>
          {message.isStreaming && !message.content ? (
            thinkingMessage ? (
              <div className="cold-start-content">
                <div className="cold-start-spinner" />
                <span>{thinkingMessage}</span>
              </div>
            ) : (
              <>
                <div className="typing-dot"></div>
                <div className="typing-dot"></div>
                <div className="typing-dot"></div>
              </>
            )
          ) : (
            <ReactMarkdown>{message.content}</ReactMarkdown>
          )}
          
          {message.isStreaming && message.content && (
            <span style={{ display: 'inline-block', width: '8px', height: '16px', background: 'var(--accent-color)', animation: 'blink 1s step-end infinite', marginLeft: '4px', verticalAlign: 'middle' }}></span>
          )}

          {!message.isStreaming && message.citations && message.citations.length > 0 && (
            <div className="citation-container">
              <div 
                className="citation-header" 
                onClick={() => setShowSources(!showSources)}
                style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-secondary)' }}
              >
                <span>Nguồn tham khảo ({message.citations.length})</span>
                {showSources ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
              </div>
              
              {showSources && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginTop: '0.5rem' }}>
                  {message.citations.map((cit, idx) => {
                    const isExpanded = expandedCitations.has(idx);
                    return (
                      <div key={idx} className="citation-card">
                        <div className="citation-card-header" onClick={() => toggleCitation(idx)}>
                          <div className="citation-card-icon"><FileText size={16} /></div>
                          <div className="citation-card-body">
                            <span className="citation-title">{cit.title || cit.chunk_id}</span>
                            <span className="citation-pages">Trang {cit.source_pages?.length ? cit.source_pages.join(', ') : 'N/A'}</span>
                          </div>
                          <div className="citation-card-toggle">
                            {isExpanded ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                          </div>
                        </div>
                        {isExpanded && cit.content && (
                          <div className="citation-card-content citation-markdown">
                            <ReactMarkdown rehypePlugins={[rehypeRaw]}>
                              {highlightKeywords(formatCitationContent(cit.content), query)}
                            </ReactMarkdown>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}
        </div>

        {isErrorMsg && (
          <button className="retry-btn" onClick={() => onRetry?.()}>
            <RotateCcw size={14} /> Thử lại
          </button>
        )}



        {!message.isStreaming && !isErrorMsg && (
          <div className="message-metadata">
            <div className="meta-actions">
              <button className="action-btn" title="Chia sẻ" onClick={handleShare}>
                <Share2 size={16} />
              </button>
              <button className={`action-btn ${feedback === 'like' ? 'active' : ''}`} title="Hữu ích" onClick={() => handleFeedbackClick('like')}>
                <ThumbsUp size={16} />
              </button>
              <button className={`action-btn ${feedback === 'dislike' ? 'active' : ''}`} title="Chưa chính xác" onClick={() => handleFeedbackClick('dislike')}>
                <ThumbsDown size={16} />
              </button>
              <button className="action-btn" title="Copy" onClick={handleCopy}>
                {copied ? <Check size={16} style={{color: 'var(--success)'}}/> : <Copy size={16} />}
              </button>
              <button className="action-btn" title="Tạo lại" onClick={() => onRegenerate?.()}>
                <RotateCcw size={16} />
              </button>
            </div>
            
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginLeft: 'auto' }}>
              {message.usedCache && (
                <span className="metadata-badge cache" title="Câu trả lời được lấy từ bộ nhớ đệm giúp tốc độ phản hồi tức thì">
                  ⚡ Từ bộ nhớ đệm
                </span>
              )}
            </div>
          </div>
        )}

        {!message.isStreaming && !isErrorMsg && message.role === 'bot' && message.suggestions && message.suggestions.length > 0 && (
          <div className="suggestion-pills-container">
            {message.suggestions.slice(0, 3).map((sugg, idx) => (
              <button key={idx} className="suggestion-pill" onClick={() => {
                if (onSuggestionClick) onSuggestionClick(sugg);
              }}>
                {sugg}
              </button>
            ))}
          </div>
        )}

        {showFeedbackModal && (
          <div className="feedback-modal-overlay" onClick={() => setShowFeedbackModal(false)}>
            <div className="feedback-modal" onClick={e => e.stopPropagation()}>
              <div className="feedback-header">
                <h4>Góp ý câu trả lời</h4>
                <button className="close-btn" onClick={() => setShowFeedbackModal(false)}>
                  <X size={16} />
                </button>
              </div>
              <p>Bot đã trả lời sai hoặc thiếu thông tin gì? (Không bắt buộc)</p>
              <textarea 
                value={feedbackText} 
                onChange={e => setFeedbackText(e.target.value)} 
                placeholder="Ví dụ: Trả lời lan man, sai thông tin học bổng..."
                rows={3}
                disabled={isSubmitting}
              />
              <div className="feedback-actions">
                <button className="btn-secondary" onClick={() => setShowFeedbackModal(false)} disabled={isSubmitting}>Bỏ qua</button>
                <button className="btn-primary" onClick={() => submitFeedbackToApi('dislike', feedbackText)} disabled={isSubmitting}>
                  {isSubmitting ? "Đang gửi..." : "Gửi góp ý"}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
