"""Server-Sent Events (SSE) streaming endpoint for real-time chat responses.

Unlike the synchronous POST /chat endpoint which waits for the full answer,
this endpoint streams tokens as they are generated by the LLM, providing
a ChatGPT-like experience with immediate visual feedback.

SSE event types:
    - metadata: Intent, strategy, citations (sent first, before any tokens).
    - token:    A chunk of generated text.
    - done:     Signals the stream is complete.
    - error:    An error occurred during processing.
"""

from __future__ import annotations

import json
import logging
import time
from typing import Any
from uuid import uuid4

from fastapi import APIRouter, Depends, Request
from fastapi.responses import StreamingResponse

from src.api.chat_controls import enforce_chat_rate_limit, validate_chat_query
from src.api.deps import get_answer_service
from src.api.schemas import ChatRequest

router = APIRouter(tags=["chat"])
logger = logging.getLogger("student_handbook_rag.api.chat_stream")


def _sse_event(event_type: str, data: dict[str, Any]) -> str:
    """Format a single Server-Sent Event."""
    payload = json.dumps(data, ensure_ascii=False, default=str)
    return f"event: {event_type}\ndata: {payload}\n\n"


@router.post("/chat/stream")
def chat_stream(
    request: ChatRequest,
    http_request: Request,
    answer_service: Any = Depends(get_answer_service),
) -> StreamingResponse:
    """Stream chat responses as Server-Sent Events (SSE).

    The client receives:
    1. An `event: metadata` with intent, strategy, and citations.
    2. Multiple `event: token` with text chunks as Gemini generates them.
    3. A final `event: done` to signal completion.
    """
    query = validate_chat_query(request.query)
    enforce_chat_rate_limit(http_request)

    request_id = uuid4().hex

    def event_generator():
        """Yield Server-Sent Events as the answer pipeline produces chunks."""
        started_at = time.perf_counter()
        final_status = "unknown"
        final_metadata: dict[str, Any] = {}
        try:
            logger.debug(
                "chat_stream_history_received",
                extra={"history_count": len(request.chat_history or [])},
            )
            stream = answer_service.answer_stream(
                query,
                chat_history=request.chat_history,
            )
            for chunk in stream:
                chunk_type = chunk.get("type", "")
                if chunk_type == "metadata":
                    chunk["request_id"] = request_id
                    final_metadata = dict(chunk)
                    final_status = str(chunk.get("status") or final_status)
                    yield _sse_event("metadata", chunk)
                elif chunk_type == "token":
                    yield _sse_event("token", {"text": chunk.get("text", "")})
                elif chunk_type == "progress":
                    yield _sse_event("progress", {"message": chunk.get("message", "")})
                elif chunk_type == "done":
                    latency_ms = round(
                        (time.perf_counter() - started_at) * 1000, 2
                    )
                    logger.info(
                        "chat_stream_completed",
                        extra={
                            "request_id": request_id,
                            "latency_ms": latency_ms,
                            "query_length": len(query),
                            "status": final_status,
                            "intent": final_metadata.get("intent"),
                            "strategy": final_metadata.get("strategy"),
                        },
                    )
                    yield _sse_event(
                        "done",
                        {"request_id": request_id, "latency_ms": latency_ms},
                    )
        except Exception:
            logger.exception(
                "chat_stream_error",
                extra={"request_id": request_id},
            )
            yield _sse_event(
                "error",
                {
                    "request_id": request_id,
                    "error_message": "Internal chatbot service error",
                },
            )

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
